core/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('palestrantes/<slug:slug>/', views.speaker_detail, name='speaker_detail'),
    path('palestras/', views.talk_list, name='talk_list'),
]

eventex/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('core.urls')),
    path('inscricao/', include('subscriptions.urls')),
    path('admin/', admin.site.urls),
]

subscriptions/urls.py
from django.urls import path
from . import views

app_name = 'subscriptions'

urlpatterns = [
    path('', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),

]

core/models.py
from django.db import models
from django.shortcuts import resolve_url as r
from core.managers import KindQuerySet, PeriodManager

# Create your models here.


class Speaker(models.Model):
    name = models.CharField('nome', max_length=50)
    slug = models.SlugField('slug')
    photo = models.URLField('foto')
    website = models.URLField('website', blank=True)
    description = models.TextField('descrição', blank=True)

    class Meta:
        verbose_name = 'Palestrante'
        verbose_name_plural = 'Palestrantes'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return r('speaker_detail', self.slug)

class Contact(models.Model):
    EMAIL = 'E'
    PHONE = 'P'
    KINDS = (
        (EMAIL, 'Email'),
        (PHONE, 'Telefone'),
    )
    speaker = models.ForeignKey('Speaker', on_delete=models.CASCADE, verbose_name='palestrante')
    kind = models.CharField('tipo', max_length=1, choices=KINDS)
    value = models.CharField('valor', max_length=100)

    objects = KindQuerySet.as_manager() #Alinhando o API com um manager customizado 
    #objects = KindContactManager()
    # objects = models.Manager()
    # emails = EmailContactManager()
    # phones = PhoneContactManager()

    class Meta:
        verbose_name = 'Contato'
        verbose_name_plural = 'Contatos'

    def __str__(self):
        return self.value

class Talk(models.Model):
    title = models.CharField('título', max_length=225)
    start = models.TimeField('começo', blank=True, null=True)
    description = models.TextField('descrição', blank=True)
    speakers = models.ManyToManyField('Speaker', verbose_name='palestrantes', blank=True)

    objects = PeriodManager()

    class Meta:
        ordering = ['start']
        verbose_name = 'palestra'
        verbose_name_plural = 'palestras'

    def __str__(self):
        return self.title


class Course(Talk):
    slots = models.IntegerField()

    class Meta:
        verbose_name = 'curso'
        verbose_name_plural = 'cursos'

subscriptions/models.py
from django.db import models
from .validators import validate_cpf


class Subscription(models.Model):
    name = models.CharField('nome', max_length=100)
    cpf = models.CharField('CPF', max_length=11, validators=[validate_cpf])
    email = models.EmailField('e-mail', blank=True)
    phone = models.CharField('telefone', max_length=20, blank=True)
    created_at = models.DateTimeField('criado em', auto_now_add=True)
    paid = models.BooleanField('pago', default=False)

    class Meta:
        verbose_name = 'inscrições'
        verbose_name_plural = 'inscrição'
        ordering = ('-created_at',)

    def __str__(self):
        return self.name

subscriptions/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import Subscription


# def validate_cpf(value):
#     if not value.isdigit():
#         raise ValidationError('CPF deve conter apenas números.', 'digits')
#     if len(value) != 11:
#         raise ValidationError('CPF deve conter 11 números.', 'length')

class SubscriptionFormOld(forms.Form):
    name  = forms.CharField(label='Nome')
    #cpf   = forms.CharField(label='Cpf', validators=[validate_cpf])
    email = forms.EmailField(label='Email', required=False)
    phone = forms.CharField(label='Telefone', required=False)

    def clean_name(self):
        name = self.cleaned_data['name']
        words = [w.capitalize() for w in name.split()]
        return ' '.join(words)
        # words = []
        # for w in name.split():
        #     words.append(w.capitalize())

    def clean(self):
        if not self.cleaned_data.get('email') and not self.cleaned_data.get('phone'):
            raise ValidationError('Informe seu telefone ou email.')
        return self.cleaned_data


class SubscriptionForm(forms.ModelForm):
    #cpf   = forms.CharField(label='Cpf', validators=[validate_cpf])
    class Meta:
        model = Subscription
        fields = ['name', 'cpf', 'email', 'phone']

    def clean_name(self):
        name = self.cleaned_data['name']
        words = [w.capitalize() for w in name.split()]
        return ' '.join(words)

    
    def clean(self):
        self.cleaned_data = super().clean()
        if not self.cleaned_data.get('email') and not self.cleaned_data.get('phone'):
            raise ValidationError('Informe seu telefone ou email.')
        return self.cleaned_data

core/views.py
from django.shortcuts import render, get_object_or_404
from core.models import Speaker, Talk, Course
# Create your views here.


def index(request):
    speakers = Speaker.objects.all()
    return render(request, 'index.html', {'speakers': speakers})


def speaker_detail(request, slug):
    speaker = get_object_or_404(Speaker, slug=slug)
    return render(request, 'core/speaker_detail.html', {'speaker': speaker})


def talk_list(request):
    # speaker = Speaker(name='Henrique Bastos', slug='henrique-bastos')
    # courses = [
    #     dict(title='Título do Curso', start='09:00',
    #          description='Descrição do curso.', speakers={'all': [speaker]})
    # ]
    context = {
        'morning_talks': Talk.objects.at_morning(),
        'afternoon_talks': Talk.objects.at_afternoon(),
        # 'morning_talks': [Talk(title='Título da Palestra', start='10:00', description='Descrição da palestra.')],
        # 'afternoon_talks': [Talk(title='Título da Palestra', start='13:00', description='Descrição da palestra.')],
    }
    return render(request, 'core/talk_list.html', context)

subscriptions/views.py
from django.core import mail
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import render, resolve_url as r
from django.template.loader import render_to_string
from django.conf import settings


from subscriptions.forms import SubscriptionForm
from subscriptions.models import Subscription


def new(request):
    if request.method == 'POST':
        return create(request)

    return empty_form(request)


def empty_form(request):
    return render(request, 'subscriptions/subscription_form.html', {'form': SubscriptionForm()})


def create(request):
    form = SubscriptionForm(request.POST)

    if not form.is_valid():
        return render(request, 'subscriptions/subscription_form.html', {'form': form})

    subscription = form.save()
    # subscription = Subscription.objects.create(**form.cleaned_data)
    # Sand email
    # subscrebe_email = form.cleaned_data['email']
    _send_mail('Confirmação de inscrição',
                settings.DEFAULT_FROM_EMAIL,
                subscription.email,
                'subscriptions/subscription_email.txt',
                {'subscription': subscription})

    # Success feedback
    # messages.success(request, 'Inscrição realizada com sucesso!')

    return HttpResponseRedirect(r('subscriptions:detail', subscription.pk))


def detail(request, pk):
    try:
        subscription = Subscription.objects.get(pk=pk)
    except Subscription.DoesNotExist:
        raise Http404
    # subscription = Subscription(
    #     name='Kelver Alves',
    #     cpf='12345678901',
    #     email='kelverwt@gmail.com',
    #     phone='84996063625',
    # )
    return render(request, 'subscriptions/subscription_detail.html', {'subscription': subscription})


def _send_mail(subject, from_, to, template_name, context):
    body = render_to_string(template_name, context)
    mail.send_mail(subject, body, from_, [from_, to])

core/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
	<head>
        <title>{% block title %}Eventex - O maior encontro hacker do mundo!{% endblock title %}</title>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="description" content="Eventex - O maior encontro hacker do mundo!">
        <meta name="author" content="wttd">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />

        <!-- Favicon -->
        <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}">

        <!-- CSS -->
        <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/basalstyle/style.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/main01.css' %}">

        <link href='http://fonts.googleapis.com/css?family=Economica:400,700' rel='stylesheet' type='text/css'>
	</head>

	<body>
        <div class="header-frame row">
            {% include 'nav.html' only %}
        </div>

        {% block content %}
        {% endblock content %}
        
    </body>
</html>

core/templates/core/speaker_detail.html
{% extends 'base.html' %}

{% block content %}
<section>
    <div class="speakers content row padding-bottom-3 desktop-8 container">
        <h2>
            <a href="{{ speaker.website }}" target="_blank">{{ speaker.name }}</a>
        </h2>
        <img class="photo" src="{{ speaker.photo }}">
        <p>
            {{ speaker.description|linebreaks }}
        </p>
    </div>

</section>

{% endblock %}

core/templates/core/talk_list.html
{% extends 'base.html' %}

{% block content %}
<section>
    <div class="talks content row padding-bottom-3 desktop-12 container">
        <h2>Manhã</h2>
        {% for talk in morning_talks %}
            {% include 'core/talk_list_snippet.html' with talk=talk only %}
            {% empty %}
            <p>Ainda não existem palestras pela manhã.</p>
        {% endfor %}

        <h2>Tarde</h2>
        {% for talk in afternoon_talks %}
            {% include 'core/talk_list_snippet.html' with talk=talk only %}
            {% empty %}
            <p>Ainda não existem palestras a tarde.</p>
        {% endfor %}
    </div>
</section>
{% endblock %}

core/templates/core/talk_list_snippet.html
<h3>{{ talk.start|date:'H:i' }} - {{ talk.title }}</h3>
    <h4>Por
        {% for speaker in talk.speakers.all %}
            <a href="{{ speaker.get_absolute_url }}">{{ speaker.name }}</a>
        {% endfor %}
    </h4>
<p>{{ talk.description }}</p>

core/templates/index.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
        <title>Eventex - O maior encontro hacker do mundo!</title>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="description" content="Eventex - O maior encontro hacker do mundo!">
        <meta name="author" content="wttd">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />

        <!-- Favicon -->
        <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}">

        <!-- CSS -->
        <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/basalstyle/style.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/main01.css' %}">

        <link href='http://fonts.googleapis.com/css?family=Economica:400,700' rel='stylesheet' type='text/css'>

        <script src="https://maps.googleapis.com/maps/api/js?v=3.exp"></script>


        <script src="{% static 'js/jquery-1.11.0.min.js' %}"></script>
        <script src="{% static 'js/jquery.stellar.min.js' %}"></script>
        <script src="{% static 'js/smooth-scroll.js' %}"></script>
        <script src="js/retina-1.1.0.min.js' %}"></script>
        <script src="{% static 'js/main.js' %}"></script>


	</head>

	<body>

        <div class="header-frame header-frame-absolute  row">
            {% include 'nav.html' only %}
        </div>

      	<!-- TOP -->
        <section id="top" data-stellar-background-ratio="0.5">
        	<div class="countdown text-align-center row desktop-12 container">
            	<h1 class="uppercase">Eventex</h1>
                <h3>Brasil</h3>
            </div>
        </section>

        <!-- OVERVIEW -->
        <section id="overview">
        	<div class="overview text-align-center row desktop-12 min-h-15 padding-top-2 container">
            	<i class="fa fa-5x fa-globe"></i>
            	<h2>A Conferência</h2>
                <p class="lead">A maior reunião de hackers do mundo.<br>Reunindo profissionais e entusiastas dos quatro <br>cantos do planeta, o <em>Eventex</em> é o lugar onde você precisa estar.</p>
            	<p><a class="btn-basic btn-blue" data-scroll href="#register">Garanta a sua vaga!</a></p>
            </div>
        </section>

        <section id="speakers">
            <div class="speakers text-align-center row desktop-8 padding-bottom-2 container">
                <h2>Palestrantes Convidados</h2>
                {% for speaker in speakers %}
                    <div class="desktop-4">
                        <img src="{{ speaker.photo }}">
                        <h4>
                            <a href="{{ speaker.get_absolute_url }}">
                                {{ speaker.name }}
                            </a>                            
                        </h4>
                    </div>
                {% endfor %}
            </div>
        </section>

        <!-- SPONSORS -->
        <section id="sponsors">
        	<div class="sponsors text-align-center row desktop-12 min-h-28 padding-bottom-2 container">

                <h2>Patrocinadores</h2>

                <h3>Gold</h3>
                <div class="sponsor-slider min-h-6">
                    <img class="img-responsive" src="{% static 'img/sponsor-gold-01.png' %}" alt="logo">
                    <img class="img-responsive" src="{% static 'img/sponsor-gold-02.png' %}" alt="logo">
                    <img class="img-responsive" src="{% static 'img/sponsor-gold-03.png' %}" alt="logo">

                </div>

                <h3>Silver</h3>
                <div class="sponsor-slider min-h-6 margin-bottom-1">
                	<img class="img-responsive" src="{% static 'img/sponsor-silver-01.png' %}" alt="logo">
                    <img class="img-responsive" src="{% static 'img/sponsor-silver-02.png' %}" alt="logo">
                    <img class="img-responsive" src="{% static 'img/sponsor-silver-03.png' %}" alt="logo">
                    <img class="img-responsive" src="{% static 'img/sponsor-silver-04.png' %}" alt="logo">
                    <img class="img-responsive" src="{% static 'img/sponsor-silver-05.png' %}" alt="logo">
                    <img class="img-responsive" src="{% static 'img/sponsor-silver-06.png' %}" alt="logo">
                </div>

                <h3>Seja um patrocinador</h3>
                <p>Interessado? Descubra as oportunidades e benefícios.</p>
                <a class="btn-basic btn-blue" href="mailto:contato@eventex.com.br?Subject=Patrocínio">informe-se</a>

            </div>
        </section>

        <!-- REGISTER -->
        <section id="register">
            <div class="register row">
                <div class="text-align-center row desktop-12 padding-top-2 min-h-14 container">
                	<h2>Inscrição</h2>
                	<h3>Inscrições abertas</h3>
                	<a class="btn-basic btn-blue" href="{% url 'subscriptions:new' %}">Inscrevase já</a>
                </div>
            </div>
        </section>

        <!-- VENUE -->
        <section id="venue">
            <div class="row min-h-10">

                <div id="map-canvas"></div>
                <div class="row desktop-12 container">
                    <div class="venue row">
                        <div class="venue-address desktop-4 gutter">
                            <h2>Bar Samba Caffé</h2>
                            <p>Melhor que qualquer centro de convenções.</p>
                            <p class="address">
                                <i class="fa fa-2x fa-map-marker fa-inverse"></i>
                                Rua do Ouvidor 23, Centro<br>
                                Rio de Janeiro, RJ
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </body>
</html>

core/templates/nav.html
<header class="header header-inline min-h-3 row desktop-12 container" role="banner">

    <div class="site-logo">
        <h1><a href="{% url 'index' %}" rel="home">Eventex</h1>
        <p class="site-description screen-reader-only">O maior encontro hacker do mundo!</p>
    </div>

    <nav class="nav-inline" role="navigation">
        <a href="javascript:void(0);" class="nav-mobile"><i class="fa fa-bars"></i></a>
        <ul>
            <li><a data-scroll href="{% url 'index' %}#overview">Conferência</a></li>
            <li><a data-scroll href="{% url 'talk_list' %}">Palestras</a></li>
            <li><a data-scroll href="{% url 'index' %}#speakers">Palestrantes</a></li>
            <li><a data-scroll href="{% url 'index' %}#sponsors">Patrocinadores</a></li>
            <li><a data-scroll href="{% url 'index' %}#register">Inscrição</a></li>
            <li><a data-scroll href="{% url 'index' %}#venue">Local</a></li>
        </ul>
    </nav>

</header>

subscriptions/templates/subscriptions/subscription_detail.html
{% extends 'base.html' %}


{% block content %}
 <!-- OVERVIEW -->
 <section>
    <div class="content row padding-bottom-3 desktop-12 container">
        <h1>Olá, {{ subscription.name }} Muito obrigada por se inscrever no Eventex.</h1>
        <div class="desktop-6">
            <p>Esses foram os dados que você nos forneceu na sua inscrição:</p>
            <ul>
                <li>{{ subscription.name }}</li>
                <li>Cpf: {{ subscription.cpf }}</li>
                <li>Email: {{ subscription.email }}</li>
                <li>Telefone: {{ subscription.phone }}</li>
            </ul>
            <p>Em até 48 horas úteis nossa equipe entrará
               em contato com você para concluirmos a sua
               matrícula.</p>
            <p>Atenciosamente,</p>
            --
            <p><b>Morena</b></p>
        </div>
    </div>
</section>
</body>
{% endblock content %}

subscriptions/templates/subscriptions/subscription_form.html
{% extends 'base.html' %}

{% block content %}
 <!-- OVERVIEW -->
 <section>
    <div class="content row padding-bottom-3 desktop-12 container">
        <h1>Formulário de Inscrição</h1>
        <div class="desktop-6">
            <form action="." novalidate method="post">
                {% csrf_token %}
                {{ form.non_field_errors }}
                <div class="form-row label-block input-text">
                    <label for="{{ form.name.id_for_label }}">{{ form.name.label }}</label>
                    {{ form.name.errors }}
                    {{ form.name }}
                </div>
                <div class="form-row label-block input-text">
                    <label for="{{ form.cpf.id_for_label }}">{{ form.cpf.label }}</label>
                    {{ form.cpf.errors }}
                    {{ form.cpf }}
                </div>
                <div class="form-row label-block input-text">
                    <label for="{{ form.email.id_for_label }}">{{ form.email.label }}</label>
                    {{ form.email.errors }}
                    {{ form.email }}
                </div>
                <div class="form-row label-block input-text">
                    <label for="{{ form.phone.id_for_label }}">{{ form.phone.label }}</label>
                    {{ form.phone.errors }}
                    {{ form.phone }}
                </div>
                <p class="btn-row"><input type="submit" value="Enviar!"/></p>
            </form>
        </div>
    </div>
</section>
</body>
{% endblock content %}

wttd/share/jupyter/nbconvert/templates/base/celltags.j2
{%- macro celltags(cell) -%}
    {% if cell.metadata.tags | length > 0 -%}
        {% for tag in (cell.metadata.tags) -%}
            {{ (' celltag_' ~ tag) | escape_html -}}
        {%- endfor -%}
    {%- endif %}
{%- endmacro %}

wttd/share/jupyter/nbconvert/templates/base/display_priority.j2
{%- extends 'base/null.j2' -%}

{#display data priority#}


{%- block data_priority scoped -%}
    {%- for type in output.data | filter_data_type -%}
        {%- if type == 'application/pdf' -%}
            {%- block data_pdf -%}
            {%- endblock -%}
        {%- elif type == 'image/svg+xml' -%}
            {%- block data_svg -%}
            {%- endblock -%}
        {%- elif type == 'image/png' -%}
            {%- block data_png -%}
            {%- endblock -%}
        {%- elif type == 'text/html' -%}
            {%- block data_html -%}
            {%- endblock -%}
        {%- elif type == 'text/markdown' -%}
            {%- block data_markdown -%}
            {%- endblock -%}
        {%- elif type == 'image/jpeg' -%}
            {%- block data_jpg -%}
            {%- endblock -%}
        {%- elif type == 'text/plain' -%}
            {%- block data_text -%}
            {%- endblock -%}
        {%- elif type == 'text/latex' -%}
            {%- block data_latex -%}
            {%- endblock -%}
        {%- elif type == 'application/javascript' -%}
            {%- block data_javascript -%}
            {%- endblock -%}
        {%- elif type == 'application/vnd.jupyter.widget-view+json' -%}
            {%- block data_widget_view -%}
            {%- endblock -%}
        {%- else -%}
            {%- block data_other -%}
            {%- endblock -%}
        {%- endif -%}
    {%- endfor -%}
{%- endblock data_priority -%}

wttd/share/jupyter/nbconvert/templates/base/jupyter_widgets.html.j2
{%- macro jupyter_widgets(widgets_cdn_url, html_manager_semver_range, widget_renderer_url='') -%}

<script>
(function() {
  function addWidgetsRenderer() {
    var mimeElement = document.querySelector('script[type="application/vnd.jupyter.widget-view+json"]');
    var scriptElement = document.createElement('script');
    {% if widget_renderer_url %}
    var widgetRendererSrc = '{{ widget_renderer_url }}';
    {% else %}
    var widgetRendererSrc = '{{ widgets_cdn_url }}@jupyter-widgets/html-manager@{{ html_manager_semver_range }}/dist/embed-amd.js';
    {%endif %}
    var widgetState;

    // Fallback for older version:
    try {
      widgetState = mimeElement && JSON.parse(mimeElement.innerHTML);

      if (widgetState && (widgetState.version_major < 2 || !widgetState.version_major)) {
        {% if widget_renderer_url %}
        var widgetRendererSrc = '{{ widget_renderer_url }}';
        {% else %}
        var widgetRendererSrc = '{{ widgets_cdn_url }}@jupyter-js-widgets@*/dist/embed.js';
        {%endif %}
      }
    } catch(e) {}

    scriptElement.src = widgetRendererSrc;
    document.body.appendChild(scriptElement);
  }

  document.addEventListener('DOMContentLoaded', addWidgetsRenderer);
}());
</script>

{%- endmacro %}

wttd/share/jupyter/nbconvert/templates/base/mathjax.html.j2
{%- macro mathjax(url="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/latest.js?config=TeX-AMS_CHTML-full,Safe") -%}
    <!-- Load mathjax -->
    <script src="{{url}}"> </script>
    <!-- MathJax configuration -->
    <script type="text/x-mathjax-config">
    init_mathjax = function() {
        if (window.MathJax) {
        // MathJax loaded
            MathJax.Hub.Config({
                TeX: {
                    equationNumbers: {
                    autoNumber: "AMS",
                    useLabelIds: true
                    }
                },
                tex2jax: {
                    inlineMath: [ ['$','$'], ["\\(","\\)"] ],
                    displayMath: [ ['$$','$$'], ["\\[","\\]"] ],
                    processEscapes: true,
                    processEnvironments: true
                },
                displayAlign: 'center',
                CommonHTML: {
                    linebreaks: {
                    automatic: true
                    }
                }
            });

            MathJax.Hub.Queue(["Typeset", MathJax.Hub]);
        }
    }
    init_mathjax();
    </script>
    <!-- End of mathjax configuration -->
{%- endmacro %}

wttd/share/jupyter/nbconvert/templates/markdown/index.md.j2
{% extends 'base/display_priority.j2' %}


{% block in_prompt %}
{% endblock in_prompt %}

{% block output_prompt %}
{%- endblock output_prompt %}

{% block input %}
```
{%- if 'magics_language' in cell.metadata  -%}
    {{ cell.metadata.magics_language}}
{%- elif 'name' in nb.metadata.get('language_info', {}) -%}
    {{ nb.metadata.language_info.name }}
{%- endif %}
{{ cell.source}}
```
{% endblock input %}

{% block error %}
{{ super() }}
{% endblock error %}

{% block traceback_line %}
{{ line | indent | strip_ansi }}
{% endblock traceback_line %}

{% block execute_result %}

{% block data_priority scoped %}
{{ super() }}
{% endblock %}
{% endblock execute_result %}

{% block stream %}
{{ output.text | indent }}
{% endblock stream %}

{% block data_svg %}
    {% if "filenames" in output.metadata %}
![svg]({{ output.metadata.filenames['image/svg+xml'] | path2url }})
    {% else %}
![svg](data:image/svg;base64,{{ output.data['image/svg+xml'] }})
    {% endif %}
{% endblock data_svg %}

{% block data_png %}
    {% if "filenames" in output.metadata %}
![png]({{ output.metadata.filenames['image/png'] | path2url }})
    {% else %}
![png](data:image/png;base64,{{ output.data['image/png'] }})
    {% endif %}
{% endblock data_png %}

{% block data_jpg %}
    {% if "filenames" in output.metadata %}
![jpeg]({{ output.metadata.filenames['image/jpeg'] | path2url }})
    {% else %}
![jpeg](data:image/jpeg;base64,{{ output.data['image/jpeg'] }})
    {% endif %}
{% endblock data_jpg %}

{% block data_latex %}
{{ output.data['text/latex'] }}
{% endblock data_latex %}

{% block data_html scoped %}
{{ output.data['text/html'] }}
{% endblock data_html %}

{% block data_markdown scoped %}
{{ output.data['text/markdown'] }}
{% endblock data_markdown %}

{% block data_text scoped %}
{{ output.data['text/plain'] | indent }}
{% endblock data_text %}

{% block markdowncell scoped %}
{{ cell.source }}
{% endblock markdowncell %}

{% block unknowncell scoped %}
unknown type  {{ cell.type }}
{% endblock unknowncell %}

wttd/share/jupyter/nbconvert/templates/python/index.py.j2
{%- extends 'null.j2' -%}

{%- block header -%}
#!/usr/bin/env python
# coding: utf-8
{% endblock header %}

{% block in_prompt %}
{% if resources.global_content_filter.include_input_prompt -%}
    # In[{{ cell.execution_count if cell.execution_count else ' ' }}]:
{% endif %}
{% endblock in_prompt %}

{% block input %}
{{ cell.source | ipython2python }}
{% endblock input %}

{% block markdowncell scoped %}
{{ cell.source | comment_lines }}
{% endblock markdowncell %}

wttd/share/jupyter/nbconvert/templates/reveal/base.html.j2
{%- extends 'lab/base.html.j2' -%}
{% from 'cellslidedata.j2' import cellslidedata %}

{%- block any_cell scoped -%}
{%- if cell.metadata.get('slide_start', False) -%}
<section {{ cellslidedata(cell) }}>
{%- endif -%}
{%- if cell.metadata.get('subslide_start', False) -%}
<section {{ cellslidedata(cell) }}>
{%- endif -%}
{%- if cell.metadata.get('fragment_start', False) -%}
<div class="fragment" {{ cellslidedata(cell) }}>
{%- endif -%}

{%- if cell.metadata.slide_type == 'notes' -%}
<aside class="notes">
{{ super() }}
</aside>
{%- elif cell.metadata.slide_type == 'skip' -%}
{%- else -%}
{{ super() }}
{%- endif -%}

{%- if cell.metadata.get('fragment_end', False) -%}
</div>
{%- endif -%}
{%- if cell.metadata.get('subslide_end', False) -%}
</section>
{%- endif -%}
{%- if cell.metadata.get('slide_end', False) -%}
</section>
{%- endif -%}
{%- endblock any_cell -%}

wttd/share/jupyter/nbconvert/templates/reveal/cellslidedata.j2
{%- macro cellslidedata(cell) -%}
    {% if cell.metadata.slideshow | length > 0 -%}
        {% if cell.metadata.slideshow.data | length > 0 -%}
            {% for key in (cell.metadata.slideshow.data) -%}
                {{- (' data_' ~ key)|replace("_", "-") -}}="{{- cell.metadata.slideshow.data[key]|escape_html -}}"
            {%- endfor -%}
        {%- endif %}
    {%- endif %}
{%- endmacro %}

wttd/share/jupyter/nbconvert/templates/script/script.j2
{%- extends 'null.j2' -%}

{% block input %}
{{ cell.source }}
{% endblock input %}

wttd/share/jupyter/nbconvert/templates/webpdf/index.pdf.j2
{%- extends 'lab/index.html.j2' -%}